### ISSUE TITLE
Dependency missing

### ISSUE THREAD

**Issue by rollwhistler** [SAM-IT/yii2-csv-formatter#1]
Hi,

I needed to add:

use yii\web\ResponseFormatterInterface;

In the CsvResponseFormatter.php in order for it to work. But after that works perfectly! thank you!

**Comment by SamMousa** [comment]
Van can you make a pr?

**Comment by SamMousa** [comment]
@rollwhistler Sorry for the delay, next time feel free to ^bump.

I've fixed it and released v1.0.0 --> note that this version no longer supports php < 5.5.
